import './globals.css'
import { Inter } from 'next/font/google'
import QueryProvider from './lib/QueryProvider'
import { ProviderUI } from './components/ProviderUI'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} w-[100%] h-screen`}>
       
          <QueryProvider>
                <ProviderUI>
                     {children}
                 </ProviderUI>
          </QueryProvider>
      
      </body>
    </html>
  )
}
