import './globals.css'
import { Inter } from 'next/font/google'
import QueryProvider from './lib/QueryProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} max-w-[100%] max-h-screen`}>
          <QueryProvider>
                     {children}
          </QueryProvider>
      </body>
    </html>
  )
}
